// Comprehensive currency list — all OpenExchangeRates supported currencies (ISO 4217).
// Used in the FX comparator so users can pick any corridor (e.g. GBP→ARS).
export interface CurrencyInfo {
  code: string;
  name: string;
  flag: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: "USD", name: "US Dollar", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", flag: "🇬🇧" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾" },
  { code: "VES", name: "Venezuelan Bolívar", flag: "🇻🇪" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴" },
  { code: "PYG", name: "Paraguayan Guaraní", flag: "🇵🇾" },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹" },
  { code: "HNL", name: "Honduran Lempira", flag: "🇭🇳" },
  { code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮" },
  { code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷" },
  { code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦" },
  { code: "CUP", name: "Cuban Peso", flag: "🇨🇺" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲" },
  { code: "TTD", name: "Trinidad Dollar", flag: "🇹🇹" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿" },
  { code: "RWF", name: "Rwandan Franc", flag: "🇷🇼" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹" },
  { code: "XOF", name: "West African CFA Franc", flag: "🌍" },
  { code: "XAF", name: "Central African CFA Franc", flag: "🌍" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲" },
  { code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴" },
  { code: "MZN", name: "Mozambican Metical", flag: "🇲🇿" },
  { code: "BWP", name: "Botswana Pula", flag: "🇧🇼" },
  { code: "NAD", name: "Namibian Dollar", flag: "🇳🇦" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺" },
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧" },
  { code: "ILS", name: "Israeli Shekel", flag: "🇮🇱" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵" },
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾" },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷" },
  { code: "TWD", name: "Taiwan Dollar", flag: "🇹🇼" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲" },
  { code: "KHR", name: "Cambodian Riel", flag: "🇰🇭" },
  { code: "LAK", name: "Lao Kip", flag: "🇱🇦" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿" },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦" },
  { code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾" },
  { code: "PLN", name: "Polish Złoty", flag: "🇵🇱" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴" },
  { code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬" },
  { code: "HRK", name: "Croatian Kuna", flag: "🇭🇷" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸" },
  { code: "MKD", name: "Macedonian Denar", flag: "🇲🇰" },
  { code: "ALL", name: "Albanian Lek", flag: "🇦🇱" },
  { code: "BAM", name: "Bosnia Convertible Mark", flag: "🇧🇦" },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰" },
  { code: "ISK", name: "Icelandic Króna", flag: "🇮🇸" },
  { code: "XCD", name: "East Caribbean Dollar", flag: "🌴" },
  { code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸" },
  { code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧" },
  { code: "BZD", name: "Belize Dollar", flag: "🇧🇿" },
  { code: "BMD", name: "Bermudian Dollar", flag: "🇧🇲" },
  { code: "KYD", name: "Cayman Dollar", flag: "🇰🇾" },
  { code: "FJD", name: "Fijian Dollar", flag: "🇫🇯" },
  { code: "PGK", name: "Papua New Guinea Kina", flag: "🇵🇬" },
  { code: "WST", name: "Samoan Tala", flag: "🇼🇸" },
  { code: "TOP", name: "Tongan Paʻanga", flag: "🇹🇴" },
  { code: "SBD", name: "Solomon Islands Dollar", flag: "🇸🇧" },
  { code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺" },
  { code: "XPF", name: "CFP Franc", flag: "🇵🇫" },
  // 2026-09-03 feedback — "sigue apareciendo lo de target currency": the
  // receiving-country picker (CountryCombobox) covers all 251 territories
  // in `country-to-currency` (see countries.ts), but this list only had 113
  // currencies — any country whose local currency wasn't one of those 113
  // left the currency combobox's `value` unmatched against every option,
  // which renders the raw placeholder text instead of a code (see
  // Combobox.tsx's `selected` lookup). Confirmed by diffing every currency
  // in country-to-currency against this list: exactly the 45 below were
  // missing (Aruba, Bhutan, Brunei, Burundi, Congo-Kinshasa, etc.) — real
  // ISO 4217 currencies, not fabricated placeholders.
  { code: "ANG", name: "Netherlands Antillean Guilder", flag: "🇦🇳" },
  { code: "AWG", name: "Aruban Florin", flag: "🇦🇼" },
  { code: "BIF", name: "Burundian Franc", flag: "🇧🇮" },
  { code: "BND", name: "Brunei Dollar", flag: "🇧🇳" },
  { code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹" },
  { code: "CDF", name: "Congolese Franc", flag: "🇨🇩" },
  { code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻" },
  { code: "XCG", name: "Caribbean Guilder", flag: "🇨🇼" },
  { code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯" },
  { code: "DZD", name: "Algerian Dinar", flag: "🇩🇿" },
  { code: "ERN", name: "Eritrean Nakfa", flag: "🇪🇷" },
  { code: "FKP", name: "Falkland Islands Pound", flag: "🇫🇰" },
  { code: "GIP", name: "Gibraltar Pound", flag: "🇬🇮" },
  { code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean Franc", flag: "🇬🇳" },
  { code: "GYD", name: "Guyanese Dollar", flag: "🇬🇾" },
  { code: "HTG", name: "Haitian Gourde", flag: "🇭🇹" },
  { code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬" },
  { code: "KMF", name: "Comorian Franc", flag: "🇰🇲" },
  { code: "KPW", name: "North Korean Won", flag: "🇰🇵" },
  { code: "LRD", name: "Liberian Dollar", flag: "🇱🇷" },
  { code: "LSL", name: "Lesotho Loti", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan Dinar", flag: "🇱🇾" },
  { code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬" },
  { code: "MOP", name: "Macanese Pataca", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷" },
  { code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻" },
  { code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼" },
  { code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨" },
  { code: "SDG", name: "Sudanese Pound", flag: "🇸🇩" },
  { code: "SHP", name: "Saint Helena Pound", flag: "🇸🇭" },
  { code: "SLE", name: "Sierra Leonean Leone", flag: "🇸🇱" },
  { code: "SOS", name: "Somali Shilling", flag: "🇸🇴" },
  { code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷" },
  { code: "SSP", name: "South Sudanese Pound", flag: "🇸🇸" },
  { code: "STN", name: "São Tomé & Príncipe Dobra", flag: "🇸🇹" },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾" },
  { code: "SZL", name: "Eswatini Lilangeni", flag: "🇸🇿" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistan Manat", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian Dinar", flag: "🇹🇳" },
  { code: "YER", name: "Yemeni Rial", flag: "🇾🇪" },
  { code: "ZWG", name: "Zimbabwe Gold", flag: "🇿🇼" },
];

export const CURRENCY_BY_CODE: Record<string, CurrencyInfo> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c]),
);
