-- TOMBSTONE: este archivo tenia un timestamp fabricado que NO coincide con
-- la version real asignada por Supabase al aplicar estas migraciones.
-- El SQL original combinaba DOS migraciones remotas distintas bajo un solo
-- nombre de archivo inventado (20260825095600). Se reemplaza este contenido
-- por este comentario para evitar que una futura `supabase db push` reintente
-- aplicar SQL de datos bajo una version fantasma que nunca existio en el
-- historial remoto de Supabase (`list_migrations`).
--
-- Las migraciones reales (ya aplicadas en remoto, ahora correctamente
-- espejadas en archivos separados con sus timestamps reales) son:
--   supabase/migrations/20260825182755_load_otras_regiones_corridors_batch_final.sql
--   supabase/migrations/20260825182812_fix_ubl_tezraftaar_generic_fields.sql
--
-- Ver docs/data-sources/2026-08-25b-auditoria-cobertura-otras-regiones.md
-- para el detalle de la investigacion de drift de versiones de migracion.
