-- Reconciliation placeholder — already applied directly against production
-- (a data backfill for the delivery-method columns added just before this
-- one). See the note in
-- 20260805133747_tighten_overly_permissive_rls_policies.sql for why this
-- file is a deliberate no-op rather than a reconstruction.
