-- TOMBSTONE: este archivo tenia un timestamp fabricado (20260825100200) que
-- NO coincide con la version real asignada por Supabase al aplicar esta
-- migracion. Se reemplaza este contenido por este comentario para evitar que
-- una futura `supabase db push` reintente aplicar SQL de datos bajo una
-- version fantasma que nunca existio en el historial remoto de Supabase
-- (`list_migrations`).
--
-- La migracion real (ya aplicada en remoto, ahora correctamente espejada en
-- un archivo con su timestamp real) es:
--   supabase/migrations/20260825200312_reverify_sin_confirmar_batch4.sql
--
-- Ver docs/data-sources/2026-08-25b-auditoria-cobertura-otras-regiones.md
-- para el detalle de la investigacion de drift de versiones de migracion.
